### ISSUE TITLE
not working on live server PHP 7.0

### ISSUE THREAD

**Issue by ozgunlu** [PHPMailer/PHPMailer#1016]
I have a vds machine.

I am trying to send an email using PHPMailer. My codes, work in localhost. But in server, it does not work. Also it returns true which means sent. But no email in my mailbox. I tried different mail extensions like hotmail, gmail etc. All is same, works on localhost, not works on server.

Here is my test code :

```
<?php
class Mail {
    private $host = 'mail.xxxx.com.tr';
    private $smtp_auth = true;
    private $username = 'xxxxx@xxxx.com.tr';
    private $password = 'xxxxxxxxx';
    private $smtp_secure = 'tls';
    private $port = 587;
    private $host_name = 'Easypath';
    private $host_mail = 'xxxx@xxxx.com.tr';
    private $mail;

    public function __construct() {
        $this->mail = new PHPMailer;

        $this->mail->CharSet = 'UTF-8';
        //$this->mail->isSMTP();
        $this->mail->smtpConnect([
            'ssl' => [
                'verify_peer' => false,
                'verify_peer_name' => false,
                'allow_self_signed' => true
            ]
        ]);
        $this->mail->Host = $this->host;
        $this->mail->SMTPAuth = $this->smtp_auth;
        $this->mail->Username = $this->username;
        $this->mail->Password = $this->password;
        $this->mail->SMTPSecure = $this->smtp_secure;
        $this->mail->Port = $this->port;
    }

    public function sendMailToUser($users, $message, $sef_link) {
        foreach ($users as $user) {
            $this->mail->addAddress($user["email"], $user["author"]);

            $healer = $user["email"] . " " . $user["author"];
        }

        $body = '<div style="margin-top:0; margin-bottom:0; padding-top:0; padding-bottom:0; width:100%; background-color:#ebf0f4">' .
                    '<table width="100%" border="0" cellspacing="0" cellpadding="0" align="center">' .
                        '<tbody>' .
                            '<tr>' .
                                '<td bgcolor="#ebf0f4">' .
                                    '<table width="620" border="0" cellspacing="0" cellpadding="0" align="center" class="x_scale">' .
                                        '<tbody>' .
                                            '<tr>' .
                                                '<td height="60">&nbsp;</td>' .
                                            '</tr>' .
                                            '<tr>' .
                                                '<td align="center"><div style="display: inline-block;"><a><img src="cid:easypath_logo" border="0" style="max-width:150px; display:inline-block"><span class="_fc_3 owaimg" style="display: none;"> </span><span class="_fc_4 o365buttonLabel" id="_ariaId_467" style="display: none;"></span></a></div> </td>' .
                                            '</tr>' .
                                            '<tr>' .
                                                '<td height="18">&nbsp;</td>' .
                                            '</tr>' .
                                            '<tr>' .
                                                '<td height="24">&nbsp;</td>' .
                                            '</tr>' .
                                        '</tbody>' .
                                    '</table>' .
                                '</td>' .
                            '</tr>' .
                        '</tbody>' .
                    '</table>' .
                    '<table width="100%" border="0" cellspacing="0" cellpadding="0" align="center">' .
                        '<tbody>' .
                            '<tr>' .
                                '<td bgcolor="#ebf0f4">' .
                                    '<table width="620" bgcolor="#FFFFFF" border="0" cellspacing="0" cellpadding="0" align="center">' .
                                        '<tbody>' .
                                            '<tr>' .
                                                '<td height="54">&nbsp;</td>' .
                                            '</tr>' .
                                            '<tr>' .
                                                '<td>' .
                                                    '<table width="520" border="0" cellspacing="0" cellpadding="0" align="center" class="x_scale">' .
                                                        '<tbody>' .
                                                            '<tr>' .
                                                                '<td align="center" style="font-family:\'source_sans_proregular\',Helvetica,Arial,sans-serif; font-size:20px; line-height:30px; color:#4a4a4a">' .
                                                                'BİLDİRİM' .
                                                                '</td>' .
                                                            '</tr>' .
                                                            '<tr>' .
                                                                '<td height="30">&nbsp;</td>' .
                                                            '</tr>' .
                                                            '<tr>' .
                                                                '<td height="18">' .
                                                                    '<table width="20" border="0" cellspacing="0" cellpadding="0" align="center">' .
                                                                        '<tbody>' .
                                                                            '<tr>' .
                                                                                '<td height="1" bgcolor="#d8d8d8" style="font-size:1px"></td>' .
                                                                            '</tr>' .
                                                                        '</tbody>' .
                                                                    '</table>' .
                                                                '</td>' .
                                                            '</tr>' .
                                                            '<tr>' .
                                                                '<td height="30">&nbsp;</td>' .
                                                            '</tr>' .
                                                            '<tr>' .
                                                                '<td align="left" style="font-family:\'source_sans_proregular\',Helvetica,Arial,sans-serif; font-size:16px; line-height:30px; color:#4a4a4a">' .
                                                                    '<span style="font-size:16px;">Merhaba,' .
                                                                        '<br>' .
                                                                        $message .
                                                                    '</span>' .
                                                                '</td>' .
                                                            '</tr>' .
                                                            '<tr>' .
                                                                '<td height="54">&nbsp;</td>' .
                                                            '</tr>' .
                                                        '</tbody>' .
                                                    '</table>' .
                                                '</td>' .
                                            '</tr>' .
                                            '<tr>' .
                                                '<td width="620" height="60" bgcolor="#69c0af" style="text-align: center">' .
                                                    '<a href="http://easypath.argenit.com.tr/digital-slide/'.$sef_link.'" target="_blank" style="background-color:#69c0af; font-size:15px; color:#FFF; text-decoration:none; display:block; text-align:center; font-family:\'source_sans_prosemibold\',Helvetica,Arial,sans-serif; text-transform:uppercase; line-height:60px">OLGUYU GÖRÜNTÜLE</a>' .
                                                '</td>' .
                                            '</tr>' .
                                        '</tbody>' .
                                    '</table>' .
                                '</td>' .
                            '</tr>' .
                        '</tbody>' .
                    '</table>' .
                    '<table width="100%" border="0" cellspacing="0" cellpadding="0" align="center">' .
                        '<tbody>' .
                            '<tr>' .
                                '<td bgcolor="#ebf0f4">' .
                                    '<table width="620" border="0" cellspacing="0" cellpadding="0" align="center" class="x_scale">' .
                                        '<tbody>' .
                                            '<tr>' .
                                                '<td height="30">&nbsp;</td>' .
                                            '</tr>' .
                                            '<tr>' .
                                                '<td align="center" style="font-family:\'source_sans_prosemibold\',Helvetica,Arial,sans-serif; font-size:12px; line-height:24px; color:#919191">' .
                                                    '© Easypath 2017&nbsp;&nbsp;|&nbsp;&nbsp;All Rights Reserved.' .
                                                '</td>' .
                                            '</tr>' .
                                            '<tr>' .
                                                '<td height="48">&nbsp;</td>' .
                                            '</tr>' .
                                        '</tbody>' .
                                    '</table>' .
                                '</td>' .
                            '</tr>' .
                        '</tbody>' .
                    '</table>' .
                '</div>';


        $this->mail->setFrom($this->host_mail, $this->host_name);


        $this->mail->isHTML(true);

        $this->mail->Subject = 'Easypath Bildirim';
        $this->mail->AddEmbeddedImage('../../assets/layout/images/logo.png', 'easypath_logo');
        $this->mail->msgHTML($body);

        if(!$this->mail->send())
        return  $this->mail->ErrorInfo;
            return $healer;
    }
}

require '../libs/PHPMailer/PHPMailerAutoload.php';

$user[0]["email"] = "ozgun_unlu@hotmail.com";
$user[0]["author"] = "Özgün ÜNLÜ";

$obj = new Mail();
$result = $obj->sendMailToUser($user, 'selam canısı', "sef-link");
var_dump($result);
```
I tried to comment out $mail->isSMTP() but does not work.

**Comment by r0073rr0r** [comment]
Please include Debug logs, not just code.

**Comment by Synchro** [comment]
Follow what it says in [the troubleshooting guide](https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting). First thing - set `$this->mail->SMTPDebug = 2`, and read all the other stuff it suggests. The most likely problem is that your ISP blocks outbound SMTP - it's very common.

**Comment by ozgunlu** [comment]
2017-03-28 07:14:57	Connection: opening to localhost:25, timeout=300, options=array (
                   	                    'ssl' => 
                   	                    array (
                   	                      'verify_peer' => false,
                   	                      'verify_peer_name' => false,
                   	                      'allow_self_signed' => true,
                   	                    ),
                   	                  )
2017-03-28 07:14:57	Connection: opened
2017-03-28 07:14:57	SERVER -> CLIENT: 220 argenit.com.tr ESMTP Exim 4.84_2 Tue, 28 Mar 2017 10:14:57 +0300
2017-03-28 07:14:57	CLIENT -> SERVER: EHLO easypath.argenit.com.tr
2017-03-28 07:14:57	SERVER -> CLIENT: 250-argenit.com.tr Hello localhost [::1]
                   	                  250-SIZE 52428800
                   	                  250-8BITMIME
                   	                  250-PIPELINING
                   	                  250 HELP
{"data":"ozgun_unlu@hotmail.com \u00d6zg\u00fcn \u00dcNL\u00dc"}2017-03-28 07:14:57	CLIENT -> SERVER: QUIT
2017-03-28 07:14:57	SERVER -> CLIENT: 221 argenit.com.tr closing connection
2017-03-28 07:14:57	Connection: closed

**Comment by Synchro** [comment]
I can see that you're requesting a secure connection, but your server doesn't support it - there is no `STARTTLS` in the capabilities list, so it can't continue.  There are no AUTH methods either. Try setting `SMTPSecure = false` and `SMTPAuth = false`.

**Comment by Eternal-Infinity** [comment]
@ozgunlu: and in case you use true credentials in the test-code, you should mask it ASAP here

**Comment by ozgunlu** [comment]
@Eternal-Infinity Thank you, i forgot it.

It works with GMAIL. It seems to server problem.
Thank you for helping.

**Comment by Eternal-Infinity** [comment]
@ozgunlu: you're welcome. maybe you should change your password now, just in case.

**Comment by vaishnavhiren1993** [comment]
I saw the problem with phpmailer seance 2016 ,
i spend my 4 day but still not working .
i tried lot's of samples but its not working .
so please  share send email code .
any method any code just give me .
i am very afraid 




every time i change something there are different errors.
but commanly i saw this error

**2018-11-19 12:10:33 SMTP ERROR: Failed to connect to server: No connection could be made because the target machine actively refused it. (10061)
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

Fatal error: Uncaught PHPMailer\PHPMailer\Exception: SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting in C:\xampp\htdocs\email\PHPMailer-master\src\PHPMailer.php:1775 Stack trace: #0 C:\xampp\htdocs\email\PHPMailer-master\src\PHPMailer.php(1516): PHPMailer\PHPMailer\PHPMailer->smtpSend('Date: Mon, 19 N...', 'hello\r\n') #1 C:\xampp\htdocs\email\PHPMailer-master\src\PHPMailer.php(1352): PHPMailer\PHPMailer\PHPMailer->postSend() #2 C:\xampp\htdocs\email\mail3.php(33): PHPMailer\PHPMailer\PHPMailer->send() #3 {main} thrown in C:\xampp\htdocs\email\PHPMailer-master\src\PHPMailer.php on line 1775**
