### ISSUE TITLE
SMTP and GMail/OAUTH

### ISSUE THREAD

**Issue by fdiengdoh** [PHPMailer/PHPMailer#1102]
First of All thank you for this wonderful script.

Now, coming to my problem, I was trying to set up the OAUTH for GMAIL, everything is working fine up to getting the refresh token using `get_oauth_token.php`. Now, when ever I try to send test mail using the `gmail_xoauth.phps` example, it wont work. I tried on local server and live server both. 

On local server this error is displayed:
```
SERVER -> CLIENT: 220 smtp.gmail.com ESMTP f2sm20681090pgc.17 - gsmtp
CLIENT -> SERVER: EHLO oas
SERVER -> CLIENT: 250-smtp.gmail.com at your service, [45.120.72.8]250-SIZE 35882577250-8BITMIME250-STARTTLS250-ENHANCEDSTATUSCODES250-PIPELINING250-CHUNKING250 SMTPUTF8
CLIENT -> SERVER: STARTTLS
SERVER -> CLIENT: 220 2.0.0 Ready to start TLS
CLIENT -> SERVER: EHLO oas
SERVER -> CLIENT: 250-smtp.gmail.com at your service, [45.120.72.8]250-SIZE 35882577250-8BITMIME250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH250-ENHANCEDSTATUSCODES250-PIPELINING250-CHUNKING250 SMTPUTF8
```
`Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 60: SSL certificate problem: unable to get local issuer certificate (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in D:\WebDev\hstd\hostnet\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:187 Stack trace: #0 D:\WebDev\hstd\hostnet\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 D:\WebDev\hstd\hostnet\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 D:\WebDev\hstd\hostnet\vendor\guzzlehttp\guzzle\src\Handler\CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #3 D:\WebDev\hstd\hostnet\vendor\guzzlehttp\guzzle in D:\WebDev\hstd\hostnet\vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php on line 187`

On live server only the first part of Message is displayed.

Now, I finally gave up as I couldn't make it work. I tried searching here and on stackoverflow, I couldn't find any solution. So, I stick to SMTP only. 

SMTP seems to work on localhost after allowing "Non Secure App" in Gmail. But when I tried on a live site, it doesn't work . Finally, I was able to find this solution on stackoverflow as follows.

> Go to link - https://accounts.google.com/b/0/DisplayUnlockCaptcha then click allow access button Reason : google does not allow any program to login automatically in a user's a/c for security reasons.

So, I thought as long as I can't use OAUTH I'd just share this problem if anyone encountered similar problem as me and may find this solution good.

Still I wish the OAUTH works. If anyone got it working I would appreciate your help.

**Comment by fdiengdoh** [comment]
UPDATE: The Oauth works on a free Gmail account. The first account I used was from Google Apps for education, and it seems our Admin block some access and that's why it wasn't working.  Anyway as of now I'll use my free gmail account.
