### ISSUE TITLE
 SMTP ERROR: Failed to connect to server

### ISSUE THREAD

**Issue by neon670** [PHPMailer/PHPMailer#1459]
# Problem description
So, I have been using phpmailer on my sites for about few months now with no issues. Now am getting error messages when submitting a form to send an email. Nothing was change nor updated, contacted my hosting provider and they stated that the phpmailer.php file was broken. I updated the file from github to to double check i have the most recent version. So, all my forms on my sites are getting an error message when trying to send any mail. 
# Code to reproduce

```php
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
$mail = new PHPMailer(true);
 $mail->SMTPDebug = 2;                                 // Enable verbose debug output
    $mail->isSMTP();                                      // Set mailer to use SMTP
    $mail->Host = 'smtp.gmail.com';  // Specify main and backup SMTP servers
    $mail->SMTPAuth = true;                               // Enable SMTP authentication
    $mail->Username = 'myemail';                 // SMTP username
    $mail->Password = 'mypassword';                           // SMTP password
    $mail->SMTPSecure = 'ssl';                            // Enable TLS encryption, `ssl` also accepted
    $mail->Port = 465;
	$mail->CharSet = 'UTF-8';
```
in my controller file:

```php
case "contact":
	if ($_POST['email']!=''){
	$to=$adminemail;
	$toname=$adminname;
	$from=$adminemail;
	$fname=$adminname;
	
	$subject="Contact Form from ".$currentnetwork;
	$mmm = "Name : ".$_POST['name']."<br/>Email :  ".$_POST['email']."<br/>Company :  ".$_POST['company']."<br/>";
	$mmm .= "Message : ".$_POST['message']."<br/>";
	$mmm .="<br/>End of Message";

	sendsmtp($from,$fname,$to, $toname,$subject,$mmm);
	$msg="Message Sent";
	header ("location:\contact");exit;}
break;
```

# Debug output
```
2018-05-15 06:48:31 SMTP ERROR: Failed to connect to server: (0)
SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting

Fatal error: Uncaught exception 'PHPMailer\PHPMailer\Exception' with message 'SMTP connect() failed. https://github.com/PHPMailer/PHPMailer/wiki/Troubleshooting'
in /home/src/PHPMailer.php:1584 Stack trace: #0 /home/src/PHPMailer.php(1358): PHPMailer\PHPMailer\PHPMailer->smtpSend('Date: Tue, 15 M...', 'Name : noe<br/>...')
#1 /home/src/PHPMailer.php(1211): PHPMailer\PHPMailer\PHPMailer->postSend()
#2 /home/controller/controller.php(72): PHPMailer\PHPMailer\PHPMailer->send()
#3 /home/controller/controller.php(950): sendsmtp('info@email.c...', 'admin', 'info@email.c...', 'admin', 'Contact Form fr...', 'Name : noe<br/>...')
#4 /home/index.php(22): include('/home/...')
#5 {main} thrown in /home/src/PHPMailer.php on line 1584
```

**Comment by Synchro** [comment]
You've enabled exceptions without a try/catch block (hence your uncaught exception), and it's getting a straightforward connection failure, which is down to your network, not your script. Do what it says in the troubleshooting guide to diagnose your issue.
