### ISSUE TITLE
Uncaught exception

### ISSUE THREAD

**Issue by matimaini** [PHPMailer/PHPMailer#1486]
```
<?php
			//use PHPMailer\PHPMailer\PHPMailer;
			use PHPMailer\PHPMailer\Exception;

			require '.\includes\Exception.php';
			require '.\includes\PHPMailer.php';
			require '.\includes\SMTP.php';
				
				function enviarEmailTFS($email,$subject,$message)
						{

							/** generales para los 2*/
									
							/** usando PHPMailer*/
							
							$mail = new PHPMailer\PHPMailer\PHPMailer(true);    // Passing `true` enables exceptions
							$mail->SMTPDebug = 0;                               // Enable verbose debug output
							
							$mail->CharSet = "utf-8";
							$mail->setLanguage('es','../includes/');
							$mail->isSMTP();                                    // Set mailer to use SMTP
							$mail->Host = 'mail.eiva.com.ar';					//'mail.eiva.com.ar';  // Specify main and backup SMTP servers
							$mail->SMTPAuth = true;                             // Enable SMTP authentication
							
							$mail->Username = 'XXXX@XXX.com.ar';				//'X';                 // SMTP username
							$mail->Password = 'XXXXX';     						// SMTP password
							$mail->SMTPSecure = 'tls';                          // Enable TLS encryption, `ssl` also accepted
							$mail->Port = 25;//25;                              // TCP port to connect to
							$mail->SMTPOptions = array(
														'ssl' => array(
														'verify_peer' => false,
														'verify_peer_name' => false,
														'allow_self_signed' => true
																		)
														); 
							$mail->setFrom('mmaini@eiva.com.ar');
							$mail->addAddress($email);     						// Add a recipient
							$mail->addReplyTo('soporte@eiva.com.ar');
							$mail->isHTML(true);                                // Set email format to HTML
							$mail->Subject =  $subject;
							$mail->Body    = $message;
							

							if(!$mail->send()) {
								return false;
								echo 'El correo no se pudo enviar.';
								echo 'Error: ' . $mail->ErrorInfo;
							} else {
								return true;
								echo 'El correo se envió correctamente';
							}
							
					
						}
						
				$count_correo_pendiente= sqlsrv_fetch_array($count_correo_pendientes,SQLSRV_FETCH_ASSOC,SQLSRV_SCROLL_NEXT);
				for ($i=1;$i<=$count_correo_pendiente['count'];$i++)
				{
					$correo_pendiente= sqlsrv_fetch_array($correo_pendientes,SQLSRV_FETCH_ASSOC,SQLSRV_SCROLL_NEXT);
				
					$email = $correo_pendiente['alternativo'];
					$subject = "Soporte registrado: ".$correo_pendiente['titulo'].".";
					$message = "Estimados: Su soporte fue registrado con numero ".$correo_pendiente['numero'].".";

				enviarEmailTFS($email, $subject, $message);
				
				}
?>
```

Result:

> 
Fatal error: Uncaught exception 'PHPMailer\PHPMailer\Exception' with message 'SMTP Error: Could not connect to SMTP host.' in C:\xampp\htdocs\Gerencia\includes\PHPMailer.php:1930 Stack trace: #0 C:\xampp\htdocs\Gerencia\includes\PHPMailer.php(1757): PHPMailer\PHPMailer\PHPMailer->smtpConnect(Array) #1 C:\xampp\htdocs\Gerencia\includes\PHPMailer.php(1513): PHPMailer\PHPMailer\PHPMailer->smtpSend('Date: Thu, 28 J...', 'Estimados: Su s...') #2 C:\xampp\htdocs\Gerencia\includes\PHPMailer.php(1352): PHPMailer\PHPMailer\PHPMailer->postSend() #3 C:\xampp\htdocs\Gerencia\correo.php(78): PHPMailer\PHPMailer\PHPMailer->send() #4 C:\xampp\htdocs\Gerencia\correo.php(103): enviarEmailTFS('matinob.drc@gma...', 'Soporte registr...', 'Estimados: Su s...') #5 {main} thrown in C:\xampp\htdocs\Gerencia\includes\PHPMailer.php on line 1930

**Comment by Synchro** [comment]
Yes, that’s exactly what happens when you tell PHPMailer to throw exceptions and then don’t catch them. Refer to the troubleshooting guide for how to diagnose your problem, but my first guess would be that your host blocks outbound SMTP.
