### ISSUE TITLE
Gmail OAuth2 stuck at "SERVER -> CLIENT", no email send, no error

### ISSUE THREAD

**Issue by RemcoMi** [PHPMailer/PHPMailer#1706]
# Problem description
I compiled PHPMailer in Composer, uploaded the Vendor directory to my Synology NAS with WEB Station PHP 7.0 and OpenSSL module activated. After getting the OAuth refresh token from GMail, I tried to use the example. Unfortuantely, the output doesn't show any error but mails are neither send.

# Code to reproduce
```
<?php echo (extension_loaded('openssl')?'SSL loaded':'SSL not loaded')."\n"; ?>
<?php
/**
 * This example shows how to send via Google's Gmail servers using XOAUTH2 authentication.
 */
//Import PHPMailer classes into the global namespace
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\OAuth;
// Alias the League Google OAuth2 provider class
use League\OAuth2\Client\Provider\Google;
//SMTP needs accurate times, and the PHP time zone MUST be set
//This should be done in your php.ini, but this is how to do it if you don't have access to that
date_default_timezone_set('Etc/UTC');
//Load dependencies from composer
//If this causes an error, run 'composer install'
require '../vendor/autoload.php';
//Create a new PHPMailer instance
$mail = new PHPMailer;
//Tell PHPMailer to use SMTP
$mail->isSMTP();
//Enable SMTP debugging
// 0 = off (for production use)
// 1 = client messages
// 2 = client and server messages
$mail->SMTPDebug = 2;
//Set the hostname of the mail server
$mail->Host = 'smtp.gmail.com';
//Set the SMTP port number - 587 for authenticated TLS, a.k.a. RFC4409 SMTP submission
$mail->Port = 587;
//Set the encryption system to use - ssl (deprecated) or tls
$mail->SMTPSecure = 'tls';
//Whether to use SMTP authentication
$mail->SMTPAuth = true;
//Set AuthType to use XOAUTH2
$mail->AuthType = 'XOAUTH2';
//Fill in authentication details here
//Either the gmail account owner, or the user that gave consent
$email = 'info@XXXXXX.nl';
$clientId = 'XXXXX-7gvnbXXXXXXXXXXXos7r2.apps.googleusercontent.com';
$clientSecret = 'IMlXXXXXXXXXXXX4qzR';
//Obtained by configuring and running get_oauth_token.php
//after setting up an app in Google Developer Console.
$refreshToken = '1/kNqiZXXXXXXXXXXXXXXXXX2B-EXXXXiN_-51__Q';
//Create a new OAuth2 provider instance
$provider = new Google(
    [
        'clientId' => $clientId,
        'clientSecret' => $clientSecret,
    ]
);
//Pass the OAuth provider instance to PHPMailer
$mail->setOAuth(
    new OAuth(
        [
            'provider' => $provider,
            'clientId' => $clientId,
            'clientSecret' => $clientSecret,
            'refreshToken' => $refreshToken,
            'userName' => $email,
        ]
    )
);
//Set who the message is to be sent from
//For gmail, this generally needs to be the same as the user you logged in as
$mail->setFrom($email, 'First Last');
//Set who the message is to be sent to
$mail->addAddress('XXXXX@XXXXXX.nl', 'John Doe');
//Set the subject line
$mail->Subject = 'PHPMailer GMail XOAUTH2 SMTP test';
//Read an HTML message body from an external file, convert referenced images to embedded,
//convert HTML into a basic plain-text alternative body
$mail->CharSet = 'utf-8';
//$mail->msgHTML(file_get_contents('contentsutf8.html'), __DIR__);
//Replace the plain text body with one created manually
$mail->isHTML(true);
$html = 'Plain text body';
$mail->Body = $html;
$mail->AltBody = strip_tags($html);
//Attach an image file
//$mail->addAttachment('images/phpmailer_mini.png');
//send the message, check for errors
if (!$mail->send()) {
    echo "Mailer Error: " . $mail->ErrorInfo;
} else {
    echo "Message sent!";
}
?>
```
# Debug output

> SSL loaded 2019-04-13 19:13:30 SERVER -> CLIENT: 220 smtp.gmail.com ESMTP XXXXXXXX.63 - gsmtp
2019-04-13 19:13:30 CLIENT -> SERVER: EHLO XXXXXXX.diskstation.me
2019-04-13 19:13:30 SERVER -> CLIENT: 250-smtp.gmail.com at your service, [XX.XXX.XXX.XXX]250-SIZE 35882577250-8BITMIME250-STARTTLS250-ENHANCEDSTATUSCODES250-PIPELINING250-CHUNKING250 SMTPUTF8
2019-04-13 19:13:30 CLIENT -> SERVER: STARTTLS
2019-04-13 19:13:30 SERVER -> CLIENT: 220 2.0.0 Ready to start TLS
2019-04-13 19:13:30 CLIENT -> SERVER: EHLO XXXXXXX.diskstation.me
2019-04-13 19:13:30 SERVER -> CLIENT: 250-smtp.gmail.com at your service, [XX.XXX.XXX.XXX]250-SIZE 35882577250-8BITMIME250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH250-ENHANCEDSTATUSCODES250-PIPELINING250-CHUNKING250 SMTPUTF8

**Comment by RemcoMi** [comment]
When I switch back to PHP 5.6 (not sure if this is related):
`Fatal error: Uncaught exception 'League\OAuth2\Client\Provider\Exception\IdentityProviderException' with message 'invalid_client' in /volume2/web/vendor/league/oauth2-google/src/Provider/Google.php:117 Stack trace: #0 /volume2/web/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(628): League\OAuth2\Client\Provider\Google->checkResponse(Object(GuzzleHttp\Psr7\Response), Array) #1 /volume2/web/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(537): League\OAuth2\Client\Provider\AbstractProvider->getParsedResponse(Object(GuzzleHttp\Psr7\Request)) #2 /volume2/web/vendor/phpmailer/phpmailer/src/OAuth.php(115): League\OAuth2\Client\Provider\AbstractProvider->getAccessToken(Object(League\OAuth2\Client\Grant\RefreshToken), Array) #3 /volume2/web/vendor/phpmailer/phpmailer/src/OAuth.php(127): PHPMailer\PHPMailer\OAuth->getToken() #4 /volume2/web/vendor/phpmailer/phpmailer/src/SMTP.php(530): PHPMailer\PHPMailer\OAuth->getOauth64() #5 /volume2/web/vendor/phpmailer/phpmailer/src/PHPMailer.php(1958): PHPMailer in /volume2/web/vendor/league/oauth2-google/src/Provider/Google.php on line 117`

**Comment by RemcoMi** [comment]
> When I switch back to PHP 5.6 (not sure if this is related):
> 
> > Fatal error: Uncaught exception 'League\OAuth2\Client\Provider\Exception\IdentityProviderException' with message 'invalid_client' in /volume2/web/vendor/league/oauth2-google/src/Provider/Google.php:117 Stack trace: #0 /volume2/web/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(628): League\OAuth2\Client\Provider\Google->checkResponse(Object(GuzzleHttp\Psr7\Response), Array) #1 /volume2/web/vendor/league/oauth2-client/src/Provider/AbstractProvider.php(537): League\OAuth2\Client\Provider\AbstractProvider->getParsedResponse(Object(GuzzleHttp\Psr7\Request)) #2 /volume2/web/vendor/phpmailer/phpmailer/src/OAuth.php(115): League\OAuth2\Client\Provider\AbstractProvider->getAccessToken(Object(League\OAuth2\Client\Grant\RefreshToken), Array) #3 /volume2/web/vendor/phpmailer/phpmailer/src/OAuth.php(127): PHPMailer\PHPMailer\OAuth->getToken() #4 /volume2/web/vendor/phpmailer/phpmailer/src/SMTP.php(530): PHPMailer\PHPMailer\OAuth->getOauth64() #5 /volume2/web/vendor/phpmailer/phpmailer/src/PHPMailer.php(1958): PHPMailer in /volume2/web/vendor/league/oauth2-google/src/Provider/Google.php on line 117

This helped me forward: needed a new client ID.
