### ISSUE TITLE
No Exception handling when incorrect SMTP credentials are used

### ISSUE THREAD

**Issue by websitedesignby** [PHPMailer/PHPMailer#1815]
# Problem description

PHPMailer should use exception handling when incorrect SMTP credentials are used. The current behavior crashes the entire application when incorrect SMTP credentials are used. 

# Code to reproduce

Use an incorrect SMTP username or password and test.

Fatal error: Uncaught PHPMailer\PHPMailer\Exception: PHPMailer\PHPMailer\Exception: SMTP Error: Could not authenticate. in /users/ross/sites/xoadmin/xoadmin/vendor/phpmailer/phpmailer/src/PHPMailer.php:1960 Stack trace: #0 /users/ross/sites/xoadmin/xoadmin/vendor/phpmailer/phpmailer/src/PHPMailer.php(1774): PHPMailer\PHPMailer\PHPMailer->smtpConnect(Array) #1 /users/ross/sites/xoadmin/xoadmin/vendor/phpmailer/phpmailer/src/PHPMailer.php(1516): PHPMailer\PHPMailer\PHPMailer->smtpSend('Date: Thu, 22 A...', '<strong>Tested:...') #2 /users/ross/sites/xoadmin/xoadmin/vendor/phpmailer/phpmailer/src/PHPMailer.php(1352): PHPMailer\PHPMailer\PHPMailer->postSend() #3 /users/ross/sites/xoadmin/xoadmin/lib/EmailSender.php(152): PHPMailer\PHPMailer\PHPMailer->send() #4 /users/ross/sites/xoadmin/xoadmin/public_html/test_email.php(19): EmailSender->send() #5 {main} in /users/ross/sites/xoadmin/xoadmin/lib/EmailSender.php:154 Stack trace: #0 /users/ross/sites/xoadmin/xoadmin/public_html/test_email.php(19): EmailSender->send() #1 {main} in /users/ross/sites/xoadmin/xoadmin/lib/EmailSender.php on line 154

# Debug output

2019-08-22 18:24:47 SERVER -> CLIENT: 220 smtp.gmail.com ESMTP b5sm208311qkk.78 - gsmtp
2019-08-22 18:24:47 CLIENT -> SERVER: EHLO local.selfinflictedmusic.com
2019-08-22 18:24:47 SERVER -> CLIENT: 250-smtp.gmail.com at your service, [2601:6c1:4080:2b5c:c582:4d71:c84b:2a0c]250-SIZE 35882577250-8BITMIME250-STARTTLS250-ENHANCEDSTATUSCODES250-PIPELINING250-CHUNKING250 SMTPUTF8
2019-08-22 18:24:47 CLIENT -> SERVER: STARTTLS
2019-08-22 18:24:47 SERVER -> CLIENT: 220 2.0.0 Ready to start TLS
2019-08-22 18:24:47 CLIENT -> SERVER: EHLO local.selfinflictedmusic.com
2019-08-22 18:24:48 SERVER -> CLIENT: 250-smtp.gmail.com at your service, [2601:6c1:4080:2b5c:c582:4d71:c84b:2a0c]250-SIZE 35882577250-8BITMIME250-AUTH LOGIN PLAIN XOAUTH2 PLAIN-CLIENTTOKEN OAUTHBEARER XOAUTH250-ENHANCEDSTATUSCODES250-PIPELINING250-CHUNKING250 SMTPUTF8
2019-08-22 18:24:48 CLIENT -> SERVER: AUTH LOGIN
2019-08-22 18:24:48 SERVER -> CLIENT: 334 VXNlcm5hbWU6
2019-08-22 18:24:48 CLIENT -> SERVER: <credentials hidden>
2019-08-22 18:24:48 SERVER -> CLIENT: 334 UGFzc3dvcmQ6
2019-08-22 18:24:48 CLIENT -> SERVER: <credentials hidden>
2019-08-22 18:24:48 SERVER -> CLIENT: 535-5.7.8 Username and Password not accepted. Learn more at535 5.7.8 https://support.google.com/mail/?p=BadCredentials b5sm208311qkk.78 - gsmtp
2019-08-22 18:24:48 SMTP ERROR: Password command failed: 535-5.7.8 Username and Password not accepted. Learn more at535 5.7.8 https://support.google.com/mail/?p=BadCredentials b5sm208311qkk.78 - gsmtp
SMTP Error: Could not authenticate.
2019-08-22 18:24:48 CLIENT -> SERVER: QUIT
2019-08-22 18:24:48 SERVER -> CLIENT: 221 2.0.0 closing connection b5sm208311qkk.78 - gsmtp
SMTP Error: Could not authenticate.

**Comment by Synchro** [comment]
This is exactly as designed - If you ask PHPMailer to throw exceptions, it’s up to you to catch them.

**Comment by websitedesignby** [comment]
My apologies. I am fixing my code.
