### ISSUE TITLE
composer install error

### ISSUE THREAD

**Issue by Kuass** [PHPMailer/PHPMailer#2236]
I installed composer on Ubuntu to use PHPMailer and entered the following command.

```
root@test:/home# composer require phpmailer/phpmailer
Deprecation Notice: Required parameter $path follows optional parameter $schema in /usr/share/php/JsonSchema/Constraints/UndefinedConstraint.php:62
Deprecation Notice: Required parameter $path follows optional parameter $schema in /usr/share/php/JsonSchema/Constraints/UndefinedConstraint.php:108
Deprecation Notice: Method ReflectionParameter::getClass() is deprecated in /usr/share/php/Composer/Repository/RepositoryManager.php:129
Deprecation Notice: Method ReflectionParameter::getClass() is deprecated in /usr/share/php/Composer/Repository/RepositoryManager.php:129
Do not run Composer as root/super user! See https://getcomposer.org/root for details
Warning from https://packagist.org: You are using an outdated version of Composer. Composer 2.0 is now available and you should upgrade. See https://getcomposer.org/2
Using version ^6.2 for phpmailer/phpmailer
./composer.json has been updated
Deprecation Notice: Method ReflectionParameter::getClass() is deprecated in /usr/share/php/Composer/Repository/RepositoryManager.php:129
Deprecation Notice: Method ReflectionParameter::getClass() is deprecated in /usr/share/php/Composer/Repository/RepositoryManager.php:129
Loading composer repositories with package information
Warning from https://packagist.org: You are using an outdated version of Composer. Composer 2.0 is now available and you should upgrade. See https://getcomposer.org/2
Updating dependencies (including require-dev)
PHP Fatal error:  Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters in /usr/share/php/Composer/DependencyResolver/DefaultPolicy.php:84
Stack trace:
#0 [internal function]: array_merge()
#1 /usr/share/php/Composer/DependencyResolver/DefaultPolicy.php(84): call_user_func_array()
#2 /usr/share/php/Composer/DependencyResolver/Solver.php(383): Composer\DependencyResolver\DefaultPolicy->selectPreferredPackages()
#3 /usr/share/php/Composer/DependencyResolver/Solver.php(736): Composer\DependencyResolver\Solver->selectAndInstall()
#4 /usr/share/php/Composer/DependencyResolver/Solver.php(228): Composer\DependencyResolver\Solver->runSat()
#5 /usr/share/php/Composer/Installer.php(473): Composer\DependencyResolver\Solver->solve()
#6 /usr/share/php/Composer/Installer.php(227): Composer\Installer->doInstall()
#7 /usr/share/php/Composer/Command/RequireCommand.php(183): Composer\Installer->run()
#8 /usr/share/php/Symfony/Component/Console/Command/Command.php(252): Composer\Command\RequireCommand->execute()
#9 /usr/share/php/Symfony/Component/Console/Application.php(946): Symfony\Component\Console\Command\Command->run()
#10 /usr/share/php/Symfony/Component/Console/Application.php(248): Symfony\Component\Console\Application->doRunCommand()
#11 /usr/share/php/Composer/Console/Application.php(251): Symfony\Component\Console\Application->doRun()
#12 /usr/share/php/Symfony/Component/Console/Application.php(148): Composer\Console\Application->doRun()
#13 /usr/share/php/Composer/Console/Application.php(100): Symfony\Component\Console\Application->run()
#14 /usr/bin/composer(59): Composer\Console\Application->run()
#15 {main}
  thrown in /usr/share/php/Composer/DependencyResolver/DefaultPolicy.php on line 84

Fatal error: Uncaught ArgumentCountError: array_merge() does not accept unknown named parameters in /usr/share/php/Composer/DependencyResolver/DefaultPolicy.php:84
Stack trace:
#0 [internal function]: array_merge()
#1 /usr/share/php/Composer/DependencyResolver/DefaultPolicy.php(84): call_user_func_array()
#2 /usr/share/php/Composer/DependencyResolver/Solver.php(383): Composer\DependencyResolver\DefaultPolicy->selectPreferredPackages()
#3 /usr/share/php/Composer/DependencyResolver/Solver.php(736): Composer\DependencyResolver\Solver->selectAndInstall()
#4 /usr/share/php/Composer/DependencyResolver/Solver.php(228): Composer\DependencyResolver\Solver->runSat()
#5 /usr/share/php/Composer/Installer.php(473): Composer\DependencyResolver\Solver->solve()
#6 /usr/share/php/Composer/Installer.php(227): Composer\Installer->doInstall()
#7 /usr/share/php/Composer/Command/RequireCommand.php(183): Composer\Installer->run()
#8 /usr/share/php/Symfony/Component/Console/Command/Command.php(252): Composer\Command\RequireCommand->execute()
#9 /usr/share/php/Symfony/Component/Console/Application.php(946): Symfony\Component\Console\Command\Command->run()
#10 /usr/share/php/Symfony/Component/Console/Application.php(248): Symfony\Component\Console\Application->doRunCommand()
#11 /usr/share/php/Composer/Console/Application.php(251): Symfony\Component\Console\Application->doRun()
#12 /usr/share/php/Symfony/Component/Console/Application.php(148): Composer\Console\Application->doRun()
#13 /usr/share/php/Composer/Console/Application.php(100): Symfony\Component\Console\Application->run()
#14 /usr/bin/composer(59): Composer\Console\Application->run()
#15 {main}
  thrown in /usr/share/php/Composer/DependencyResolver/DefaultPolicy.php on line 84
```
What's the problem?? TT

**Comment by Synchro** [comment]
This looks like you're using an old version of composer, and you may have issues with your PHP config. Either way, it doesn't look like this has anything to do with PHPMailer.
