### ISSUE TITLE
[php8] escapeshellcmd now fatal error if disabled

### ISSUE THREAD

**Issue by Pross** [PHPMailer/PHPMailer#2457]
Using latest wordpress 5.8 and having escapeshellcmd in disabled_functions ... PHP 7.4 you get the warning about it being disabled in the logs as mentioned in various other issues.

However in php8 its now a fatal error:

```
PHP Fatal error:  Uncaught Error: Call to undefined function PHPMailer\PHPMailer\escapeshellcmd() in /Users/pross/Sites/bb-test/wp-includes/PHPMailer/PHPMailer.php:1786
Stack trace:
#0 /Users/pross/Sites/bb-test/wp-includes/PHPMailer/PHPMailer.php(1879): PHPMailer\PHPMailer\PHPMailer::isShellSafe('pross@pross.org...')
#1 /Users/pross/Sites/bb-test/wp-includes/PHPMailer/PHPMailer.php(1642): PHPMailer\PHPMailer\PHPMailer->mailSend('Date: Wed, 21 J...', 'This is a multi...')
#2 /Users/pross/Sites/bb-test/wp-includes/PHPMailer/PHPMailer.php(1473): PHPMailer\PHPMailer\PHPMailer->postSend()
#3 /Users/pross/Sites/bb-test/wp-content/plugins/mailpoet/lib/Mailer/Methods/PHPMail.php(45): PHPMailer\PHPMailer\PHPMailer->send()
#4 /Users/pross/Sites/bb-test/wp-content/plugins/mailpoet/lib/Mailer/Mailer.php(67): MailPoet\Mailer\Methods\PHPMail->send(Array, 'dfsdfs <dfsdf@e...', Array)
#5 /Users/pross/Sites/bb-test/wp-content/plugins/mailpoet/lib/Subscribers/ConfirmationEmailMailer.php(126): MailPoet\Mailer\Mailer->send(Array, 'dfsdfs <dfsdf@e...', Array)
#6 /Users/pross/Sites/bb-test/wp-content/plugins/mailpoet/lib/Subscribers/ConfirmationEmailMailer.php(68): MailPoet\Subscribers\ConfirmationEmailMailer->sendConfirmationEmail(Object(MailPoet\Models\Subscriber))
#7 /Users/pross/Sites/bb-test/wp-content/plugins/mailpoet/lib/API/MP/v1/API.php(383): MailPoet\Subscribers\ConfirmationEmailMailer->sendConfirmationEmailOnce(Object(MailPoet\Models\Subscriber))
#8 /Users/pross/Sites/bb-test/wp-content/plugins/mailpoet/lib/API/MP/v1/API.php(200): MailPoet\API\MP\v1\API->_sendConfirmationEmail(Object(MailPoet\Models\Subscriber))
#9 /Users/pross/Sites/bb-test/wp-content/plugins/mailpoet/lib/API/MP/v1/API.php(327): MailPoet\API\MP\v1\API->subscribeToLists('11', Array, Array)
#10 /Users/pross/Repos/bb-plugin/classes/class-fl-builder-service-mailpoet.php(200): MailPoet\API\MP\v1\API->addSubscriber(Array, Array)
#11 /Users/pross/Repos/bb-plugin/modules/subscribe-form/subscribe-form.php(180): FLBuilderServiceMailPoet->subscribe(Object(stdClass), 'dfsdf@example.c...', 'dfsdfs')
#12 /Users/pross/Sites/bb-test/wp-includes/class-wp-hook.php(303): FLSubscribeFormModule->submit('')
#13 /Users/pross/Sites/bb-test/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array)
#14 /Users/pross/Sites/bb-test/wp-includes/plugin.php(470): WP_Hook->do_action(Array)
#15 /Users/pross/Sites/bb-test/wp-admin/admin-ajax.php(187): do_action('wp_ajax_fl_buil...')
#16 {main}
  thrown in /Users/pross/Sites/bb-test/wp-includes/PHPMailer/PHPMailer.php on line 1786
```

**Comment by Synchro** [comment]
How is this a PHPMailer issue?
