### ISSUE TITLE
Php8.1.3 compatibility issues?

### ISSUE THREAD

**Issue by ZiXia1** [PHPMailer/PHPMailer#2669]
I have used a plug-in in my blog, but the plug-in references PHPMailer, and there are some problems, may I ask how to solve them?

```
string(11) "xxxx@qq.com"
trim(): Argument #1 ($string) must be of type string, array given
TypeError: trim():  Argument #1 ($string) must be of type string,  array given in /web/no.cn/usr/plugins/Notice/libs/phpmailer/PHPMailer.php:1100
Stack trace:
#0 /web/no.cn/usr/plugins/Notice/libs/phpmailer/PHPMailer.php(1100): trim()
#1 /web/no.cn/usr/plugins/Notice/libs/phpmailer/PHPMailer.php(1014):  PHPMailer\PHPMailer\PHPMailer->addOrEnqueueAnAddress()
#2 /web/no.cn/usr/plugins/Notice/libs/TestAction.php(342): PHPMailer\PHPMailer\PHPMailer->addAddress()
#3 /web/no.cn/usr/plugins/Notice/libs/TestAction.php(426): TypechoPlugin\Notice\libs\TestAction->sendTestMail()
#4 /web/no.cn/var/Widget/Action.php(71): TypechoPlugin\Notice\libs\TestAction->action()
#5 /web/no.cn/var/Typecho/Widget.php(155): Widget\Action->execute()
#6 /web/no.cn/var/Typecho/Router.php(96): Typecho\Widget::widget()
#7 /web/no.cn/index.php(23): Typecho\Router::dispatch()
#8 {main}
```

**Comment by ZiXia1** [comment]
Phpmailer.php is up to date

**Comment by ZiXia1** [comment]
Using the plug-in https://github.com/RainshawGao/Typecho-Plugin-Notice

**Comment by Synchro** [comment]
That will be a bug in the TestAction.php script in that plugin, or possibly further upstream, where it is apparently trying to set an email address as an array instead of a string.
